services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'   # Porta da aplicação
      - '15672:15672' # Porta do painel de admin
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest